default_bus: default
failure_transport: failed_messages

buses:
  default: ~

transports:
  kafka:
    dsn: "kafka://localhost:29092/"
    retry_strategy:
      max_retries: 5
      delay: 500ms
      multiplier: 2
      max_delay: 5s
    options:
      topics:
        - my-topic
      group: my-group
      offset_config:
        type: earliest
      commit:
        strategy: batch
        interval: 500ms
        batch_size: 10
      pool:
        size: 3
        min_size: 2
        max_size: 10
        dynamic: true
      rebalance:
        strategy: roundrobin
      key:
        strategy: message_id

  failed_messages:
    dsn: "amqp://guest:guest@localhost:5672/"
    options:
      auto_setup: true
      exchange:
        name: failed_exchange
        type: fanout
      queues:
        failed_messages_queue: ~

routing:
  message.ExampleHelloMessage: kafka
