codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 80%
        threshold: 1%
        if_ci_failed: error

    patch:
      default:
        target: 80%
        threshold: 1%

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no

flags:
  unittests:
    paths:
      - "core/"
      - "transport/"
      - "builder/"
      - "config/"
      - "serializer/"
      - "api/"
    carryforward: true

  e2e:
    paths:
      - "tests/e2e/"
    carryforward: true

ignore:
  - "examples/"
  - "benchmarks/"
  - "**/*_test.go"
  - "tests/e2e/fixtures/"
  - "tests/e2e/helpers/"
  - "tests/mocks/"
  - "tests/helpers/"
